### PR TITLE
Update plot.py

### PR DESCRIPTION
**Pull request by gmao-jjin3**
Plot legends properly.

### CODE REVIEW

**Comment by gmao-jjin3** [comment]
f5294_fp gmi_gpm_p2_OMA_ch6

Here is an example of new legends.

**Comment by rtodling** [comment]
JJ: as you know, the bias prediction plots (the split into the predators) is only one of the plots that need this change. Did you make a change to the one showing mean (omf) stddev, obs count etc?

**Comment by gmao-msienkie** [comment]
> JJ: as you know, the bias prediction plots (the split into the predators) is only one of the plots that need this change. Did you make a change to the one showing mean (omf) stddev, obs count etc?

The plot shown is the "Analysis Summary" but the changes to the legends apply for all of the plots.  I have a set of modified plots on my pyradmon page https://gmao.gsfc.nasa.gov/intranet/personnel/msienkiewicz/new_radmon/index.php

**Comment by gmao-jjin3** [comment]
> > JJ: as you know, the bias prediction plots (the split into the predators) is only one of the plots that need this change. Did you make a change to the one showing mean (omf) stddev, obs count etc?
> 
> The plot shown is the "Analysis Summary" but the changes to the legends apply for all of the plots. I have a set of modified plots on my pyradmon page https://gmao.gsfc.nasa.gov/intranet/personnel/msienkiewicz/new_radmon/index.php

That's right. The  changes apply for all of the plots.  Thanks, Meta.

**Pull request merged**
